### PR TITLE
Refresh UI

### PR DESCRIPTION
**Pull request by valdisiljuconoks**
- Converted to Razor
- Fixed some smaller issues
- Due to web.config ignorance, decision is to distribute it expanded (no zip file).

### CODE REVIEW

**Comment by valdisiljuconoks** [comment]
This addresses #41

**Comment by seriema** [comment]
22 commits and 300 changed files, to update the UI? 👀 This will take quite some time to review. @valdisiljuconoks is there a way to split this PR so the relevant reviewers can review their part?

**Comment by valdisiljuconoks** [comment]
yeah, something similar came through my mind recently ;)

alrighty.. splitting up..

**Comment by valdisiljuconoks** [comment]
created new 2 PRs - UI refresh (+ converted to Razor) & AlloyTech sample site

**Comment by seriema** [comment]
Reviewing the other PR's instead.

**Pull request closed without merging**
