### PR TITLE
Converted to Razor, added new Shell UI

### PR DESCRIPTION
**Pull request by valdisiljuconoks**
Updated CMS package to 11.21.1

### CODE REVIEW

**Comment by valdisiljuconoks** [comment]
@seriema , @bjuris any chance to proceed here?

**Comment by seriema** [comment]
Sorry @valdisiljuconoks it should've been reviewed already. I've added it to our backlog so it'll get reviewed, latest next Monday.

**Comment by valdisiljuconoks** [comment]
thanks. after these there will be one final PR for the packaging and release... Hope that will go fast as well.

**Comment by ghost** [comment]
LGTM

**Pull request merged**
